import Image from "next/image";
import { ArrowRight } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

export default function QuizHowToUse() {
    const steps = [
        {
            title: "Step 1: Upload",
            description:
                "Upload an image, take a picture, or provide a PDF, and let our AI make flashcards for you.",
            image: "/images/image.png",
        },
        {
            title: "Step 2: Practice",
            description:
                "Review your flashcards, share, print, or export them. We support platforms like Anki and many others.",
            image: "/images/image.png",
        },
        {
            title: "Step 3: Test Yourself",
            description:
                "Enter exam mode. Test your knowledge and receive personalized feedback, generated by AI.",
            image: "/images/image.png",
        },
    ];

    return (
        <div className="w-full py-12">
            <div className="container px-4 md:px-6">
                <h3 className="text-center text-3xl font-bold">
                    AI Flashcard Generator
                </h3>
                <p className="mt-4 text-center text-muted-foreground">
                    Follow these simple steps to create effective flashcards and
                    transform your learning experience.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8 md:gap-4 relative mt-8">
                    {steps.map((step, index) => (
                        <div
                            key={index}
                            className="flex flex-col items-center text-center h-56"
                        >
                            <Card className="w-full shadow-xl">
                                <CardContent className="p-3">
                                    <Image
                                        src={step.image || "/placeholder.svg"}
                                        alt={step.title}
                                        width={200}
                                        height={150}
                                        className="rounded-lg mb-3 w-full object-cover"
                                    />
                                    <h2 className="text-2xl font-semibold mb-1">
                                        {step.title}
                                    </h2>
                                    <p className="text-lg text-muted-foreground leading-relaxed">
                                        {step.description}
                                    </p>
                                </CardContent>
                            </Card>
                            <div className="flex items-center justify-center mt-4">
                                <ArrowRight className="w-8 h-8" />
                            </div>
                        </div>
                    ))}
                </div>
                <div className="mt-12 text-center">
                    <p className="text-lg font-medium">
                        Ready to get started? Transform your study routine
                        today!
                    </p>
                </div>
            </div>
        </div>
    );
}
